image:
  repository: ghcr.io/druggeri/nut_exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

dashboard:
  enabled: false
  namespace: ""
  labels:
    # Label that config maps with dashboards should have to be added for the Grafana helm chart
    # https://github.com/grafana/helm-charts/blob/main/charts/grafana/README.md
    grafana_dashboard: "1"

serviceMonitor:
  enabled: false
  namespace: ""
  labels: {}
    # key: value
  relabelings: []
    # - replacement: "My UPS"
    #   targetLabel: ups

extraArgs: []
# - --log.level=debug

envSecret:
  NUT_EXPORTER_PASSWORD: "mypasswd"

env:
  - name: NUT_EXPORTER_SERVER
    value: "127.0.0.1"
  - name: NUT_EXPORTER_USERNAME
    value: "admin"
  # - name: NUT_EXPORTER_USERNAME
  #   valueFrom:
  #     secretKeyRef:
  #       name: nut-credentials
  #       key: username
  # - name: NUT_EXPORTER_PASSWORD
  #   valueFrom:
  #     secretKeyRef:
  #       name: nut-credentials
  #       key: password


nodeSelector: {}
# has-ups-server: yes

tolerations: []
# - key: node-role.kubernetes.io/master
#   operator: "Exists"
#   effect: NoSchedule

podAnnotations:
  prometheus.io/scrape: "false"
  prometheus.io/path: "/ups_metrics"
  prometheus.io/port: "9199"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

podHostNetwork: false

service:
  type: ClusterIP
  port: 9199

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-nut-exporter.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-nut-exporter-tls
  #    hosts:
  #      - chart-nut-exporter.local

livenessProbe:
  httpGet:
    path: /ups_metrics
    port: http
  initialDelaySeconds: 10
  failureThreshold: 5
  timeoutSeconds: 2

readinessProbe:
  httpGet:
    path: /ups_metrics
    port: http
  initialDelaySeconds: 10
  failureThreshold: 5
  timeoutSeconds: 2

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

rules:
  enabled: false
  namespace: ""
  labels: {}
    # key: value
  rules:
    - alert: UPSBatteryNeedsReplacement
      annotations:
        message: '{{ $labels.ups }} is indicating a need for a battery replacement.'
      expr: network_ups_tools_ups_status{flag="RB"} != 0
      for: 60s
      labels:
        severity: high
    - alert: UPSLowBattery
      annotations:
        message: '{{ $labels.ups }} has low battery and is running on backup. Expect shutdown soon'
      expr: network_ups_tools_ups_status{flag="LB"} == 0 and network_ups_tools_ups_status{flag="OL"} == 0
      for: 60s
      labels:
        severity: critical
    - alert: UPSRuntimeShort
      annotations:
        message: '{{ $labels.ups }} has only {{ $value | humanizeDuration}} of battery autonomy'
      expr: network_ups_tools_battery_runtime < 300
      for: 30s
      labels:
        severity: high
    - alert: UPSMainPowerOutage
      annotations:
        message: '{{ $labels.ups }} has no main power and is running on backup.'
      expr: network_ups_tools_ups_status{flag="OL"} == 0
      for: 60s
      labels:
        severity: critical
    - alert: UPSIndicatesWarningStatus
      annotations:
        message: '{{ $labels.ups }} is indicating a need for a battery replacement.'
      expr: network_ups_tools_ups_status{flag="HB"} != 0
      for: 60s
      labels:
        severity: warning
